[package]
name = "veneer"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
sc = { git = "https://github.com/joshuarli/syscall.rs", branch = "chore/use-llvm-asm" }
libc = {version = "0.2", default-features = false}
